// Importing mutilple things
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Providers } from "@/lib/components/Providers";

const geistSans = Geist({
  // A constant named giestSans is getting made
  variable: "--font-geist-sans", // creates a CSS varable for this font from next.js
  subsets: ["latin"], // Only loads the latin characters
});

const geistMono = Geist_Mono({
  // A constant named giestMono is getting made
  variable: "--font-geist-mono", // creates a CSS varable for this font from next.js
  subsets: ["latin"], // Only loads the latin characters
});

export const metadata: Metadata = {
  // Metadata is the extra information about your website
  title: "Ultimate to-do list", // The title of the tab is "Ultimate to-do list"
  description: "Generated by create next app", // The description is the words in the string
};

export default function RootLayout({
  // Defines a React component called RootLayout which makes this the default export of the file
  children, // Represents whatever you put inside the components opening and closing tags
}: Readonly<{
  // You can't accendently reassign children at any point in the function
  children: React.ReactNode; // Means that children can be any valid React thing
}>) {
  return (
    <html
      lang="en" // Sets the languge to english
    >
      <body // Main contaner of the page
        className={`        
          ${geistSans.variable} 
          ${geistMono.variable} 
          antialiased`} // Adds CSS classes to the body and uses both the geistSans and geistMono fonts
      >
        <Providers>
          {
            children // places where the content goes on the page
          }
        </Providers>
      </body>
    </html>
  );
}
